version: "3"

tasks:
  setup:
    desc: Setup
    cmds:
      - uv sync
      - task setup-dev

  build:
    desc: Build all Docker images
    cmds:
      - docker compose build

  create-worker-pool:
    cmds:
      - docker compose exec -it prefect-server prefect work-pool create celine --type docker || true

  setup-dev:
    desc: Setup development environment
    cmds:
      - uv sync
      - |
        for app in ./apps/*; do
          if [ -f "$app/requirements.txt" ]; then
            echo "Adding requirements from $app/requirements.txt"
            uv pip install -r "$app/requirements.txt"
          fi
        done
      - |
        CELINE_UTILS_PATH=../celine-utils
        if [ ! -d CELINE_UTILS_PATH ]; then
          echo "Clone celine-eu/celine-utils in $CELINE_UTILS_PATH"
          exit 0
        fi
        uv pip install -e $CELINE_UTILS_PATH

  pipeline:release:app:
    cmds:
      - .venv/bin/python scripts/bump_version.py minor {{.CLI_ARGS}}

  pipeline:release:owm:
    cmds:
      - task pipeline:release:app -- owm --commit

  pipeline:release:copernicus:
    cmds:
      - task pipeline:release:app -- copernicus --commit

  pipeline:release:osm:
    cmds:
      - task pipeline:release:app -- osm --commit

  pipeline:release:dwd:
    cmds:
      - task pipeline:release:app -- dwd --commit

  pipeline:release:om:
    cmds:
      - task pipeline:release:app -- om --commit

  pipeline:release:all:
    cmds:
      - task pipeline:release:app -- copernicus
      - task pipeline:release:app -- dwd
      - task pipeline:release:app -- om
      - task pipeline:release:app -- osm
      - task pipeline:release:app -- owm
      - |
        git add apps/*/version.txt
        git commit -m "chore: bump apps version.txt"

  pipeline:release:base:
    cmds:
      - .venv/bin/python scripts/bump_version.py minor base --commit
