version: "3"

tasks:
  setup:
    desc: Setup
    cmds:
      - uv sync
      - task setup-dev

  build:
    desc: Build all Docker images
    cmds:
      - docker compose build

  create-worker-pool:
    cmds:
      - docker compose exec -it prefect-server prefect work-pool create celine --type docker || true

  setup-dev:
    desc: Setup development environment
    cmds:
      - uv sync
      - |
        for app in ./apps/*; do
          if [ -f "$app/requirements.txt" ]; then
            echo "Adding requirements from $app/requirements.txt"
            uv pip install -r "$app/requirements.txt"
          fi
        done
      - |
        CELINE_UTILS_PATH=../celine-utils
        if [ ! -d CELINE_UTILS_PATH ]; then
          echo "Clone celine-eu/celine-utils in $CELINE_UTILS_PATH"
          exit 0
        fi
        uv pip install -e $CELINE_UTILS_PATH

  pipeline:owm:release:
    cmds:
      - .venv/bin/python scripts/bump_version.py owm minor --commit

  pipeline:copernicus:release:
    cmds:
      - .venv/bin/python scripts/bump_version.py copernicus minor --commit

  pipeline:osm:release:
    cmds:
      - .venv/bin/python scripts/bump_version.py osm minor --commit

  pipeline:dwd:release:
    cmds:
      - .venv/bin/python scripts/bump_version.py dwd minor --commit

  pipeline:om:release:
    cmds:
      - .venv/bin/python scripts/bump_version.py om minor --commit

  pipeline:release:all:
    cmds:
      - task: pipeline:copernicus:release
      - task: pipeline:dwd:release
      - task: pipeline:osm:release
      - task: pipeline:owm:release
      - task: pipeline:om:release

  pipeline:release:base:
    cmds:
      - .venv/bin/python scripts/bump_version.py base minor --commit
