name: "rec_metering"
version: "1.0.0"
config-version: 2

profile: "rec_metering"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  rec_metering:
    gold:
      +materialized: table
      +schema: gold
